/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prs;

import TableUtitlity.MyTable;
import com.mysql.jdbc.Connection;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.ListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import mymod.dbconnector;

/**
 *
 * @author wan
 */
public class MedicalRecordAnalizer extends javax.swing.JInternalFrame {

    Connection con = (Connection) dbconnector.conn();

    /**
     * Creates new form MedicalRecordAnalizer
     */
    public MedicalRecordAnalizer() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        txt_recordCount = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_from = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_to = new javax.swing.JList();
        btn_backward = new javax.swing.JButton();
        btn_forward = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_Expression = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        combo_Operand = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txt_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_CV = new javax.swing.JComboBox();
        btn_refresh = new javax.swing.JButton();
        cmd_build = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rb_OR = new javax.swing.JRadioButton();
        rb_AND = new javax.swing.JRadioButton();
        cmd_viewData = new javax.swing.JButton();
        cmd_build1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane9 = new javax.swing.JScrollPane();
        list_fieldSelectionFromTree = new javax.swing.JList();
        jPanel14 = new javax.swing.JPanel();
        btn_forward_t = new javax.swing.JButton();
        btn_backward_t = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_createData = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        combo_aggregate = new javax.swing.JComboBox();
        btn_groupby = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_aggregated = new javax.swing.JTextArea();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        list_to2 = new javax.swing.JList();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        cmd_createReport = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        combo_agre = new javax.swing.JComboBox();
        cmd_Build = new javax.swing.JButton();
        cmd_Reset = new javax.swing.JButton();
        progress = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        perodTo = new de.wannawork.jcalendar.JCalendarComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        perodFrom = new de.wannawork.jcalendar.JCalendarComboBox();
        jRadioButton3 = new javax.swing.JRadioButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Medical Record Analizer");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 51));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel7FocusGained(evt);
            }
        });

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Patient Data");
        jRadioButton5.setActionCommand("p");
        jRadioButton5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton5ItemStateChanged(evt);
            }
        });

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton6.setText("Diagnosis Data");
        jRadioButton6.setActionCommand("d");
        jRadioButton6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton6ItemStateChanged(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        list_from.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Fields", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        list_from.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(list_from);

        list_to.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selected Fields", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        list_to.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        list_to.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_to.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_toMouseClicked(evt);
            }
        });
        list_to.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_toValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(list_to);

        btn_backward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/56.gif"))); // NOI18N
        btn_backward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backwardActionPerformed(evt);
            }
        });

        btn_forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/57.gif"))); // NOI18N
        btn_forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forwardActionPerformed(evt);
            }
        });

        ta_Expression.setColumns(20);
        ta_Expression.setRows(5);
        ta_Expression.setToolTipText("To build the criteria expression, select the field from selected fields and select operand and value from text boxes and press <<Write>> button");
        ta_Expression.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Criteria Expresion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jScrollPane5.setViewportView(ta_Expression);

        combo_Operand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", "<", ">", "<>", ">=", "<=", "like", "not like", "between", " ", " " }));
        combo_Operand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_OperandItemStateChanged(evt);
            }
        });
        combo_Operand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_OperandActionPerformed(evt);
            }
        });

        jLabel4.setText("Criteria Value");

        jLabel3.setText("Operand");

        jLabel5.setText("Field Name");

        combo_CV.setEditable(true);
        combo_CV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_CVItemStateChanged(evt);
            }
        });

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.gif"))); // NOI18N
        btn_refresh.setToolTipText("Get values from database");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        cmd_build.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/54.gif"))); // NOI18N
        cmd_build.setText("Write");
        cmd_build.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmd_build.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_buildActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(combo_Operand, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_CV, javax.swing.GroupLayout.Alignment.LEADING, 0, 183, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmd_build)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmd_build, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combo_Operand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combo_CV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(btn_refresh))))
                .addGap(3, 3, 3))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup4.add(rb_OR);
        rb_OR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_OR.setText("OR");
        rb_OR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ORActionPerformed(evt);
            }
        });

        buttonGroup4.add(rb_AND);
        rb_AND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_AND.setText("AND");
        rb_AND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ANDActionPerformed(evt);
            }
        });

        cmd_viewData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmd_viewData.setForeground(new java.awt.Color(255, 51, 0));
        cmd_viewData.setText("View Data");
        cmd_viewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_viewDataActionPerformed(evt);
            }
        });

        cmd_build1.setText("Clear");
        cmd_build1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmd_build1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_build1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_viewData, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(rb_AND)
                .addGap(18, 18, 18)
                .addComponent(rb_OR)
                .addGap(32, 32, 32)
                .addComponent(cmd_build1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(cmd_viewData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(1, 1, 1))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rb_OR)
                                .addComponent(rb_AND))))
                    .addComponent(cmd_build1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton2.setText("Create an aggregate data report with these fields");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_forward, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_backward, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_forward, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(btn_backward, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton7.setText("Both");
        jRadioButton7.setActionCommand("b");
        jRadioButton7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton7ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Select Fields", new javax.swing.ImageIcon(getClass().getResource("/icon/admition.jpg")), jPanel7); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setRowHeight(32);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Data ", new javax.swing.ImageIcon(getClass().getResource("/icon/Database.gif")), jPanel4); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setFocusable(false);
        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });

        jTable2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(jTable2);

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTree1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Group Field", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 0))); // NOI18N
        jTree1.setForeground(new java.awt.Color(0, 0, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane6.setViewportView(jTree1);

        list_fieldSelectionFromTree.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selected Fields", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        list_fieldSelectionFromTree.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        list_fieldSelectionFromTree.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_fieldSelectionFromTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_fieldSelectionFromTreeMouseClicked(evt);
            }
        });
        list_fieldSelectionFromTree.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_fieldSelectionFromTreeValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(list_fieldSelectionFromTree);

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        btn_forward_t.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/54.gif"))); // NOI18N
        btn_forward_t.setText("Add");
        btn_forward_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forward_tActionPerformed(evt);
            }
        });
        jPanel14.add(btn_forward_t);

        btn_backward_t.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/55.gif"))); // NOI18N
        btn_backward_t.setText("Clear");
        btn_backward_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backward_tActionPerformed(evt);
            }
        });
        jPanel14.add(btn_backward_t);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        jButton3.setText("View Report");

        btn_createData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/process.jpg"))); // NOI18N
        btn_createData.setText("Create");
        btn_createData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createDataActionPerformed(evt);
            }
        });

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criteria Expression", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane11.setViewportView(jTextArea2);

        jPanel15.add(jScrollPane11);

        jPanel16.setLayout(new java.awt.GridLayout(2, 1));

        combo_aggregate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sum", "count", "max", "min", "last", "first", "avg" }));
        jPanel16.add(combo_aggregate);

        btn_groupby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/57.gif"))); // NOI18N
        btn_groupby.setText("Group By");
        jPanel16.add(btn_groupby);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_createData, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(286, 286, 286)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(btn_createData))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Reports", new javax.swing.ImageIcon(getClass().getResource("/icon/3d bar chart.gif")), jPanel2); // NOI18N

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Expression Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        ta_aggregated.setEditable(false);
        ta_aggregated.setColumns(20);
        ta_aggregated.setForeground(new java.awt.Color(0, 0, 153));
        ta_aggregated.setRows(5);
        ta_aggregated.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane3.setViewportView(ta_aggregated);

        jPanel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 153, 51));
        jTextArea1.setRows(5);
        jTextArea1.setText("Select fields from the list \nand select aggregate functions \nand press <Build>\nand select the group fields from the list \nand select Group by from the list of aggregate functions");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane8.setViewportView(jTextArea1);

        jPanel17.add(jScrollPane8);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        list_to2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selected Fields", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(204, 0, 0))); // NOI18N
        list_to2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        list_to2.setModel(list_to.getModel());
        list_to2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_to2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_to2MouseClicked(evt);
            }
        });
        list_to2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_to2ValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(list_to2);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );

        jPanel10.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jButton6.setText("View Data for  this Expression");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6);

        jButton7.setText("jButton7");
        jPanel10.add(jButton7);

        cmd_createReport.setText("Create Report for this Expression");
        jPanel10.add(cmd_createReport);

        jPanel18.setOpaque(false);
        jPanel18.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Aggregate Functions");
        jPanel18.add(jLabel6);

        combo_agre.setForeground(new java.awt.Color(153, 51, 0));
        combo_agre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sum", "count", "max", "min", "avg", "Group by" }));
        jPanel18.add(combo_agre);

        cmd_Build.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/57.gif"))); // NOI18N
        cmd_Build.setText("Build");
        cmd_Build.setEnabled(false);
        cmd_Build.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_BuildActionPerformed(evt);
            }
        });
        jPanel18.add(cmd_Build);

        cmd_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cross.png"))); // NOI18N
        cmd_Reset.setText("Reset");
        cmd_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_ResetActionPerformed(evt);
            }
        });
        jPanel18.add(cmd_Reset);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aggregate Data", new javax.swing.ImageIcon(getClass().getResource("/icon/Cash register.gif")), jPanel9); // NOI18N

        jLabel2.setText("To");

        jLabel1.setText("From");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setText("Diagnosis Data");
        jRadioButton4.setActionCommand("D");
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Analize");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        perodTo.setBackground(new java.awt.Color(51, 255, 51));
        perodTo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        perodTo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                perodToStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("Date");
        jRadioButton1.setActionCommand("D");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Period");
        jRadioButton2.setActionCommand("P");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });

        perodFrom.setBackground(new java.awt.Color(51, 255, 51));
        perodFrom.setDate(new java.util.Date(1365461812000L));
        perodFrom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        perodFrom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                perodFromStateChanged(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Patient Data");
        jRadioButton3.setActionCommand("P");
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perodFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(perodTo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {perodFrom, perodTo});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(perodTo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jRadioButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton4))
                        .addComponent(perodFrom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_recordCount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_recordCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String tableName;

    void fillListWithFieldsOf(String t) {
        try {
            Object[] fieldNames_d = wans_javalib.wans_MetaData.getFieldNames(con, "diagnosis_data");
            Object[] fieldNames_p = wans_javalib.wans_MetaData.getFieldNames(con, "patient_data");
            Object[] fieldNames_b = wans_javalib.wans_MetaData.getFieldNames(con, "patient_diagnosis_data_fully");
            if ("d".equals(t)) {
                list_from.setListData(fieldNames_d);
                tableName = "diagnosis_data";
            } else if ("p".equals(t)) {
                list_from.setListData(fieldNames_p);
                tableName = "patient_data";
            } else if ("b".equals(t)) {
                list_from.setListData(fieldNames_b);
                tableName = "patient_diagnosis_data_fully";
            }
            ar.clear();
            ar_to.clear();

            list_to.setListData(ar_to.toArray());

            list_to2.setListData(ar_to.toArray());
        } catch (SQLException ex) {
            Logger.getLogger(MedicalRecordAnalizer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String periodFrom = new SimpleDateFormat("yyyy-MM-dd").format(perodFrom.getDate());
        String periodTo = new SimpleDateFormat("yyyy-MM-dd").format(perodTo.getDate());

        try {
            String sql = "";
            if ("D".equals(buttonGroup2.getSelection().getActionCommand())) {
                sql = "SELECT * FROM diagnosis_data WHERE Discharge_Date between '" + periodFrom + "' and '" + periodTo + "'";
            } else {
                sql = "SELECT * FROM patient_data  WHERE Admission_Date between '" + periodFrom + "' and '" + periodTo + "'";
            }
            MyTable myTable = new MyTable(con, sql, new int[]{200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200});
            myTable.setBackground(new java.awt.Color(204, 255, 204));
            myTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            myTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            myTable.setRowHeight(32);

            jScrollPane1.remove(jTable1);
            jScrollPane1.setViewportView(myTable);
            txt_recordCount.setText("" + myTable.getModel().getRowCount());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        txt_recordCount.setText("" + jTable1.getModel().getRowCount());

    }//GEN-LAST:event_jTable1MouseClicked

    private void perodToStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_perodToStateChanged
    }//GEN-LAST:event_perodToStateChanged
    void changedatacombo() {
        if ("D".equals(buttonGroup1.getSelection().getActionCommand())) {
            perodTo.setDate(perodFrom.getDate());
            perodTo.setEnabled(false);
        } else {

            perodTo.setEnabled(true);
        }
    }
    private void perodFromStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_perodFromStateChanged
        changedatacombo();
    }//GEN-LAST:event_perodFromStateChanged

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
        changedatacombo();
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged
        changedatacombo();
    }//GEN-LAST:event_jRadioButton2StateChanged

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
    }//GEN-LAST:event_jRadioButton3ItemStateChanged
    void fillListFrom() {
        if ("p".equals(buttonGroup3.getSelection().getActionCommand())) {
            fillListWithFieldsOf("p");
        } else if ("d".equals(buttonGroup3.getSelection().getActionCommand())) {
            fillListWithFieldsOf("d");
        } else if ("b".equals(buttonGroup3.getSelection().getActionCommand())) {
            fillListWithFieldsOf("b");
        }
        clearExpression();
    }

    void clearExpression() {
        ta_Expression.setText(null);
        txt_field.setText(null);
        combo_CV.setSelectedItem(null);
        combo_Operand.setSelectedItem(null);
    }

    private TreeModel getDefaultTreeModel() {
        String sql;
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Data Tables");
        DefaultMutableTreeNode parent;
        Object[] fieldNames;

        try {
            parent = new DefaultMutableTreeNode("Patient_Data");
            root.add(parent);
            sql = "patient_data_fully";

            fieldNames = wans_javalib.wans_MetaData.getFieldNames(con, sql);

            for (int i = 0; i < fieldNames.length; i++) {
                parent.add(new DefaultMutableTreeNode(fieldNames[i]));
            }



            parent = new DefaultMutableTreeNode("Diagnosis_Data");
            root.add(parent);
            sql = "diagnosis_data_fully";

            fieldNames = wans_javalib.wans_MetaData.getFieldNames(con, sql);
            for (int i = 0; i < fieldNames.length; i++) {
                parent.add(new DefaultMutableTreeNode(fieldNames[i]));
            }

        } catch (SQLException ex) {
            Logger.getLogger(MedicalRecordAnalizer.class.getName()).log(Level.SEVERE, null, ex);
        }
        return new DefaultTreeModel(root);
    }

    private void jPanel7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel7FocusGained
    }//GEN-LAST:event_jPanel7FocusGained
    ArrayList ar_to = new ArrayList();
    ArrayList ar = new ArrayList();

//    private static final String FORWARD = "f";
//    private static final String BACKWARD = "b";
    void setListElements(String action) {
        ar.clear();
        ar_to.clear();

        ListModel model_from = list_from.getModel();


        ListModel model_to = list_to.getModel();
        for (int i = 0; i < model_from.getSize(); i++) {
            Object elementAt = model_from.getElementAt(i);

            ar.add(elementAt);

        }
        for (int i = 0; i < model_to.getSize(); i++) {
            Object elementAt = model_to.getElementAt(i);

            ar_to.add(elementAt);



        }

        if (action.equals("f")) {
            for (int i = 0; i < model_from.getSize(); i++) {
                Object elementAt = model_from.getElementAt(i);
                if (list_from.isSelectedIndex(i)) {
                    ar_to.add(elementAt);
                    //       combo_CF.addItem(elementAt);
                    ar.remove(elementAt);
                }

            }
            list_from.setListData(ar.toArray());
            list_to.setListData(ar_to.toArray());

            list_to2.setListData(ar_to.toArray());
            ar.clear();
            ar_to.clear();

        } else {
            for (int i = 0; i < model_to.getSize(); i++) {
                Object elementAt = model_to.getElementAt(i);
                if (list_to.isSelectedIndex(i)) {
                    ar.add(elementAt);
                    //       combo_CF.addItem(elementAt);
                    ar_to.remove(elementAt);
                }

            }
            list_from.setListData(ar.toArray());
            list_to.setListData(ar_to.toArray());
            list_to2.setListData(ar_to.toArray());
            ar.clear();
            ar_to.clear();
        }
    }
    private void btn_forwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forwardActionPerformed

        setListElements("f");
    }//GEN-LAST:event_btn_forwardActionPerformed

    private void jRadioButton5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton5ItemStateChanged

        fillListFrom();

    }//GEN-LAST:event_jRadioButton5ItemStateChanged

    private void jRadioButton6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton6ItemStateChanged
        fillListFrom();

    }//GEN-LAST:event_jRadioButton6ItemStateChanged

    private void btn_backwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backwardActionPerformed

        setListElements("b");


    }//GEN-LAST:event_btn_backwardActionPerformed

    private void cmd_buildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_buildActionPerformed
        String exp = "";

        try {
            String fieldname = txt_field.getText();
            String operand = combo_Operand.getSelectedItem().toString();
            String criteriavalue = combo_CV.getSelectedItem().toString();
            exp = fieldname + " " + operand + " '" + criteriavalue + "'";
            ta_Expression.append(exp);
            if ("between".equals(operand)) {
                ta_Expression.append(" and ");
                combo_Operand.setSelectedItem(" ");
                txt_field.setText(null);
                combo_CV.requestFocus();
                combo_CV.setPopupVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No Expression arguments found");
        }


    }//GEN-LAST:event_cmd_buildActionPerformed

    private void rb_ANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ANDActionPerformed
        ta_Expression.append("\n AND ");
    }//GEN-LAST:event_rb_ANDActionPerformed

    private void rb_ORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ORActionPerformed
        ta_Expression.append("\n OR ");
    }//GEN-LAST:event_rb_ORActionPerformed

    private void combo_OperandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_OperandItemStateChanged
    }//GEN-LAST:event_combo_OperandItemStateChanged

    private void combo_CVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_CVItemStateChanged
//        String v = ta_Expression.getText() + " " + combo_CV.getSelectedItem().toString();
//        ta_Expression.setText(v);
    }//GEN-LAST:event_combo_CVItemStateChanged

    private void combo_OperandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_OperandActionPerformed
    }//GEN-LAST:event_combo_OperandActionPerformed

    private void cmd_build1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_build1ActionPerformed
        clearExpression();
    }//GEN-LAST:event_cmd_build1ActionPerformed

    private void list_toValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_toValueChanged
        if (list_to.getSelectedValues().length > 0) {
            txt_field.setText(list_to.getSelectedValue().toString());
        }

    }//GEN-LAST:event_list_toValueChanged

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        if (list_to.getModel().getSize() > 0) {
            try {
                String sql = "SELECT DISTINCT " + txt_field.getText() + " FROM " + tableName + " ORDER BY " + txt_field.getText();
                wans_javalib.RecordManipulator.FilloutCombo(con, sql, combo_CV);
            } catch (SQLException ex) {
                Logger.getLogger(MedicalRecordAnalizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Select fields from the list to get values");
        }
    }//GEN-LAST:event_btn_refreshActionPerformed
    String sqlBuilt;

    void buildSql() {
        sqlBuilt = "";


        if (list_to.getModel().getSize() > 0) {


            try {




                for (int i = 0; i < list_to.getModel().getSize(); i++) {
                    if (list_to.getModel().getElementAt(i) != null) {
                        sqlBuilt = sqlBuilt + list_to.getModel().getElementAt(i) + ",\n";
                    }

                }
                sqlBuilt = sqlBuilt.substring(0, sqlBuilt.length() - 2);
                sqlBuilt = "SELECT \t\n" + sqlBuilt + "\t\n FROM \n" + tableName;
                if (!"".equals(ta_Expression.getText())) {
                    sqlBuilt = sqlBuilt + "\t\n WHERE \n" + ta_Expression.getText().trim();
                }


            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Ambiguous expression ");
            }
        }

    }
    private void cmd_viewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_viewDataActionPerformed

        buildSql();
        setTableByQueryData(sqlBuilt);
    }//GEN-LAST:event_cmd_viewDataActionPerformed
    void setTableByQueryData(String sql) {
        try {

            boolean execute = con.createStatement().execute(sql);


            MyTable myTable = new MyTable(con, sql, new int[]{200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200});
            myTable.setBackground(new java.awt.Color(204, 255, 204));
            myTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            myTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            myTable.setRowHeight(32);

            jScrollPane1.remove(jTable1);
            jScrollPane1.setViewportView(myTable);
            txt_recordCount.setText("" + myTable.getModel().getRowCount());
            jTabbedPane1.setSelectedIndex(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ambiguous expression ");
        }

    }
    private void jRadioButton7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton7ItemStateChanged
        fillListFrom();
    }//GEN-LAST:event_jRadioButton7ItemStateChanged

    private void list_toMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_toMouseClicked
        list_toValueChanged(null);

    }//GEN-LAST:event_list_toMouseClicked

    private void list_to2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_to2ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_list_to2ValueChanged

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
    }//GEN-LAST:event_jPanel2FocusGained

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        if (jTabbedPane1.getSelectedIndex() == 3) {
            jTree1.setModel(getDefaultTreeModel());
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked
    ArrayList<Object> tablelist = new ArrayList<Object>();
    ArrayList<String> selectedFieldsList = new ArrayList<String>();

    public MedicalRecordAnalizer(String title) {
        super(title);
    }
    private void list_fieldSelectionFromTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_fieldSelectionFromTreeMouseClicked
        if (list_fieldSelectionFromTree.getSelectedValues().length > 0) {
            jPanel16.setVisible(true);
        } else {
            jPanel16.setVisible(false);
        }
    }//GEN-LAST:event_list_fieldSelectionFromTreeMouseClicked

    private void list_fieldSelectionFromTreeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_fieldSelectionFromTreeValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_list_fieldSelectionFromTreeValueChanged

    private void btn_forward_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forward_tActionPerformed
        String toString = jTree1.getSelectionPath().getLastPathComponent().toString();
        //   jTree1.getSelectionModel().setSelectionMode(TreeSelectionModel.CONTIGUOUS_TREE_SELECTION);

        Object[] treeValues = treeValues(jTree1);

        for (int i = 0; i < treeValues.length; i++) {
            System.out.println("" + treeValues[i].toString());
            tablelist.add(treeValues[i]);

            String parentof = jTree1.getSelectionPaths()[i].getParentPath().getLastPathComponent().toString();
            tablelist.add(jTree1.getSelectionPaths()[i].getParentPath().getLastPathComponent());
            System.out.println("" + parentof);

            selectedFieldsList.add(jTree1.getSelectionPaths()[i].getParentPath().getLastPathComponent().toString() + "." + treeValues[i].toString());

        }

        list_fieldSelectionFromTree.setListData(selectedFieldsList.toArray());

    }//GEN-LAST:event_btn_forward_tActionPerformed

    private void btn_backward_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backward_tActionPerformed
        selectedFieldsList.clear();
        list_fieldSelectionFromTree.setListData(selectedFieldsList.toArray());
        jPanel16.setVisible(false);
    }//GEN-LAST:event_btn_backward_tActionPerformed

    private void btn_createDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_createDataActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        buildSql();
        ta_aggregated.setText(sqlBuilt);
        
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton2ActionPerformed
    String groupClause = "";
    String selectClause = "";
    private void cmd_BuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_BuildActionPerformed

        if (!"Group by".equals(combo_agre.getSelectedItem().toString()) && (list_to2.getSelectedValues().length > 0)) {
            String agre_function = combo_agre.getSelectedItem().toString();
            String fieldtoagre = list_to2.getSelectedValue().toString();

            String replace = ta_aggregated.getText().replace(fieldtoagre, agre_function + "(" + fieldtoagre + ") as " + agre_function + "Of" + fieldtoagre);
            ta_aggregated.setText(replace);
            selectClause = ta_aggregated.getText();
        } else if ("Group by".equals(combo_agre.getSelectedItem().toString()) && (list_to2.getSelectedValues().length > 0)) {
            groupClause = groupClause + list_to2.getSelectedValue().toString() + ",";
            String sqlFull = selectClause + " Group by " + groupClause.substring(0, groupClause.length() - 1);
            ta_aggregated.setText(sqlFull);
        }
    }//GEN-LAST:event_cmd_BuildActionPerformed

    private void list_to2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_to2MouseClicked
        if (list_to2.getSelectedValues().length > 0) {
            cmd_Build.setEnabled(true);
        } else {
            cmd_Build.setEnabled(false);
        }
    }//GEN-LAST:event_list_to2MouseClicked

    private void cmd_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_ResetActionPerformed
        jButton2ActionPerformed(null);
        groupClause = "";

    }//GEN-LAST:event_cmd_ResetActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed


        setTableByQueryData(ta_aggregated.getText());
    }//GEN-LAST:event_jButton6ActionPerformed
    Object[] treeValues(JTree tree) {

        tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        TreePath[] selectionPaths = tree.getSelectionPaths();
        Object[] ob = new Object[selectionPaths.length];
        for (int i = 0; i < selectionPaths.length; i++) {



            Object lastPathComponent = tree.getSelectionPaths()[i].getLastPathComponent();
            ob[i] = lastPathComponent;
        }
        return ob;
    }

    public int getModelRecCount() {
        return jTable1.getModel().getRowCount();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backward;
    private javax.swing.JButton btn_backward_t;
    private javax.swing.JButton btn_createData;
    private javax.swing.JButton btn_forward;
    private javax.swing.JButton btn_forward_t;
    private javax.swing.JButton btn_groupby;
    private javax.swing.JButton btn_refresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton cmd_Build;
    private javax.swing.JButton cmd_Reset;
    private javax.swing.JButton cmd_build;
    private javax.swing.JButton cmd_build1;
    private javax.swing.JButton cmd_createReport;
    private javax.swing.JButton cmd_viewData;
    private javax.swing.JComboBox combo_CV;
    private javax.swing.JComboBox combo_Operand;
    private javax.swing.JComboBox combo_aggregate;
    private javax.swing.JComboBox combo_agre;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTree jTree1;
    private javax.swing.JList list_fieldSelectionFromTree;
    private javax.swing.JList list_from;
    private javax.swing.JList list_to;
    private javax.swing.JList list_to2;
    private de.wannawork.jcalendar.JCalendarComboBox perodFrom;
    private de.wannawork.jcalendar.JCalendarComboBox perodTo;
    private javax.swing.JProgressBar progress;
    private javax.swing.JRadioButton rb_AND;
    private javax.swing.JRadioButton rb_OR;
    private javax.swing.JTextArea ta_Expression;
    private javax.swing.JTextArea ta_aggregated;
    private javax.swing.JTextField txt_field;
    private javax.swing.JTextField txt_recordCount;
    // End of variables declaration//GEN-END:variables

    public void persist(Object object) {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("prsPU");
        EntityManager em = emf.createEntityManager();

        em.getTransaction().begin();
        try {
            em.persist(object);
            em.getTransaction().commit();
        } catch (Exception e) {
            e.printStackTrace();
            em.getTransaction().rollback();
        } finally {
            em.close();
        }
    }
}
